### ISSUE TITLE
Typo?「挙動を検証を」「これは、これは」

### ISSUE THREAD

**Issue by liveasnotes** [heppoko/Unity_uGUI_Advance_Reference#1]
ちょっとだけ読んでみました。
タイポを見つけたのでお伝えしておきます。

> 挙動を検証を経た結果である
via https://github.com/heppoko/Unity_uGUI_Advance_Reference

> これは、これはかつて UI Elements と呼ばれていたものである。
via 本体

**Comment by heppoko** [comment]
フィードバックありがとうございます！
次回アップデートのタイミングで修正します！

**Comment by heppoko** [comment]
対応しました。
ご協力ありがとうございました！
