### ISSUE TITLE
ラインセンス情報にリンクを追記してはどうでしょうか？etc

### ISSUE THREAD

**Issue by liveasnotes** [heppoko/Unity_uGUI_Advance_Reference#2]
> Unity uGUI のライセンス については Unity UI Package の LICENSE を参照のこと。

以下のライセンスのことであれば、リンクを添えておくと、より良いかもしれません。
https://unity3d.com/legal/licenses/Unity_Companion_License

また、本体 PDF を読めば分かるのですが、GitHub 上の文章だけだと「Unity UI Package の LICENSE」が、`Packages/Unity UI` を Show in Explorer することで閲覧できるファイルであるということが分からないです。
その旨も書き添えておくと、読む際の不安が少し減って良いかもしれないです。

**Comment by heppoko** [comment]
フィードバックありがとうございます！
次回アップデートのタイミングで修正します！

**Comment by heppoko** [comment]
対応しました。
ご協力ありがとうございました！
