### ISSUE TITLE
overridePixelPerfectの説明について

### ISSUE THREAD

**Issue by Kuma00000011** [heppoko/Unity_uGUI_Advance_Reference#3]
ありがたく読ませていただいています。
細かいところですが少々混乱してしまったのでissueとして残しておきます。

以下の説明について：
> この Canvas が親 Canvas の pixelPerfect の設定を引き継ぐかどうかを取得/設定する。
> デフォルト値は true であり、つまり 親 Canvas の設定を引き継ぐ。

名前から推察するに、
親Canvasの設定を引き継ぐというより、
親Canvasから設定された値を上書きするかどうかではないでしょうか？

overridePixelPerfectがtrue（デフォルト値）、かつ、inherit（デフォルト値） --> 親Canvasの設定を引き継ぐ
overridePixelPerfectがtrue（デフォルト値）、かつ、on --> 親Canvasの設定を無視して常にon
overridePixelPerfectがfalse  --> 親Canvasの設定が使われる

**Comment by heppoko** [comment]
フィードバックありがとうございます！
次回アップデートのタイミングで修正します！

**Comment by heppoko** [comment]
対応しました。
ご協力ありがとうございました！
