### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by pushpeshkarki** [heppoko/Unity_uGUI_Advance_Reference#4]
HI,

I like to thank you for your effort in making this. However, I have a small request which I am not sure if is doable or not. I like to see if this can be translated into English? if not now, maybe sometime later in future?

**Comment by heppoko** [comment]
The English version is under consideration. Thank you for your patience!

**Comment by Bian-Sh** [comment]
Could you pls offer a editable version of this document,so that they can translate by themself if they want to.

**Comment by heppoko** [comment]
I'll consider releasing the English version first.

**Comment by pushpeshkarki** [comment]
@heppoko Any update on the English version?

**Comment by heppoko** [comment]
English version is now available!
https://github.com/heppoko/Unity_uGUI_Advance_Reference/tree/main/English
