### ISSUE TITLE
Typo on P.486 "ebGLNativeInputField"

### ISSUE THREAD

**Issue by kawai125** [heppoko/Unity_uGUI_Advance_Reference#5]
後半まだじっくり読めていないので他にもあるかもしれませんが、１か所Typoを見つけたのでご報告いたします。

P.486
   InputField の代わりに ebGLNativeInputField コンポーネントを利用することで解決できる。
    -> InputField の代わりに WebGLNativeInputField コンポーネントを利用することで解決できる。

かと思います。

UI周りの実装について、準リファレンス資料として頼りにさせていただきます。
公開ありがとうございます。

**Comment by heppoko** [comment]
フィードバックありがとうございます！
次回アップデートのタイミングで修正します！

**Comment by heppoko** [comment]
対応しました。
ご協力ありがとうございました！
